version: '3'
services:
  web:
    image: gcr.io/google_containers/klf-web:v1
    ports:
      - "9090:80"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  sidecar:
    image: gcr.io/google_containers/klf-redis-sidecar:v1
    network_mode: "host"
    depends_on:
      - redis
  autocomplete:
    image: gcr.io/google_containers/klf-autocomplete:v1
    ports:
      - "8080:8080"
