version: '2'
services:
  web:
    image: web
    #image: gcr.io/g-demo-1/web:v1
    ports:
      - "80:80"
    #depends_on:
      #- autocomplete
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  sidecar:
    image: sidecar
  autocomplete:
    image: autocomplete
    ports:
      - "8080:8080"
